package com.example.demo.models;

public enum ERole {
    ROLE_GENERAL_USER, ROLE_PLAYER, ROLE_SPARE_CAPTAIN, ROLE_LEAGUE_EXCUTIVE,
}

// INSERT INTO roles(name) VALUES('ROLE_GENERAL_USER');
// INSERT INTO roles(name) VALUES('ROLE_PLAYER');
// INSERT INTO roles(name) VALUES('ROLE_SPARE_CAPTAIN');
// INSERT INTO roles(name) VALUES('ROLE_LEAGUE_EXCUTIVE');